routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{RegisterController,LoginController,DashboardController,EventController, UserController};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/register',  [RegisterController::class, 'index'])->name('register.index');
Route::post('/register', [RegisterController::class, 'store'])->name('register.store');
Route::get('/',[LoginController::class, 'index'])->name('login');
Route::post('/login',[LoginController::class, 'store'])->name('login.store');
Route::get('/loginadmin',[LoginController::class, 'admin'])->name('login.admin');
Route::post('/loginadmin',[LoginController::class, 'storeAdmin'])->name('login.adminstore');

Route::middleware(['auth'])->group(function () {
    Route::get('/lobby',[LoginController::class, 'lobby'])->name('login.lobby');
    Route::get('perfil/{id}/edit',[LoginController::class, 'edit'])->name('login.edit');
    Route::put('{usuario}/update',[LoginController::class, 'update'])->name('login.update');
    Route::get('{id}/event-register',[LoginController::class, 'eventregister'])->name('login.eventregister');
    Route::get('/logout',[LoginController::class, 'logout'])->name('login.logout');
    Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard.index');
    Route::resources([
        'events' => EventController::class,
        'users' => UserController::class,
    ]);

    Route::post('/events/delete', [EventController::class, 'deleteEvent'])->name('events.delete');

    Route::get('/allEvents',[EventController::class, 'allEvents'])->name('events.allEvents'); 
    Route::get('/report/{id}',[EventController::class, 'report'])->name('events.report');   

    Route::post('file-import', [UserController::class, 'fileImport'])->name('file-import');
});

resources/views/admin/layouts/partials/footer.blade.php
<div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
	<div class="text-dark order-2 order-md-1">
	    <span class="text-muted fw-bold me-1">2022©</span>
		    <a href="#" target="_blank" class="text-gray-800 text-hover-primary">{{ env('APP_NAME') }}</a>
		</div>
		<!-- <ul class="menu menu-gray-600 menu-hover-primary fw-bold order-1">
			<li class="menu-item">
				<a href="https://keenthemes.com" target="_blank" class="menu-link px-2">About</a>
			</li>
			<li class="menu-item">
				<a href="https://keenthemes.com/support" target="_blank" class="menu-link px-2">Support</a>
			</li>
			<li class="menu-item">
				<a href="https://1.envato.market/EA4JP" target="_blank" class="menu-link px-2">Purchase</a>
			</li>
		</ul> -->
</div>

resources/views/admin/layouts/partials/navbar.blade.php
<div id="kt_header" style="" class="header align-items-stretch">
    <div class="container-fluid d-flex align-items-stretch justify-content-between">
        <div class="d-flex align-items-center d-lg-none ms-n3 me-1" title="Show aside menu">
			<div class="btn btn-icon btn-active-light-primary w-30px h-30px w-md-40px h-md-40px" id="kt_aside_mobile_toggle">
                <span>
                    <i class="fas fa-bars"></i>
                </span>
			</div>
		</div>
        <div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
			<a href="{{ route('dashboard.index') }}" class="d-lg-none">
		        <img alt="Logo" src="{{ asset(env('DOMAIN_LOGO_SVG')) }}" style="height: 20px" />
			</a>
		</div>
		<div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
            @include('admin.shared.breadcrumbs',['title' => $title, 'breadcrumbs' => $breadcrumbs] )
            <div class="d-flex align-items-stretch flex-shrink-0">
                <div class="d-flex align-items-stretch flex-shrink-0">
                    <div class="d-flex align-items-center ms-1 ms-lg-3">
					    <div class="btn btn-icon btn-active-light-primary position-relative w-30px h-30px w-md-40px h-md-40px" id="kt_drawer_chat_toggle">
							<span>
                                <i class="fas fa-bell icon-10x"></i>
                            </span>
							<span class="bullet bullet-dot bg-info h-6px w-6px position-absolute translate-middle top-0 start-50 animation-blink"></span>
						</div>
					</div>
                    <div class="d-flex align-items-center ms-1 ms-lg-3">
                        <div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end" data-kt-menu-flip="bottom">
                            <img src="{{ asset('/images/placeholders/user.png') }}" alt="metronic" />
                        </div>
                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-primary fw-bold py-4 fs-6 w-275px" data-kt-menu="true">
                            <div class="menu-item px-3">
                                <div class="menu-content d-flex align-items-center px-3">
                                    <div class="symbol symbol-50px me-5">
                                        <img alt="Logo" src="{{ asset('/images/placeholders/user.png') }}"/>
                                    </div>
                                    <!-- <div class="symbol symbol-circle symbol-50px overflow-hidden me-3">
										<div class="symbol-label fs-3 bg-light-primary text-primary">{{ auth()->user()->name[0] }}</div>
									</div> -->
                                    <div class="d-flex flex-column">
                                        <div class="fw-bolder d-flex align-items-center fs-5">
                                            {{ auth()->user()->name }}
                                        </div>
                                        <span class="fw-bold text-muted fs-7" style="word-break: break-all;"> {{ auth()->user()->email }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="separator my-2"></div>
                            <div class="menu-item px-5">
                                <a href="{{ route('login.logout') }}" class="menu-link px-5">Cerrar sesión</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
	    </div>
	</div>
</div>

resources/views/admin/layouts/partials/scripts.blade.php
{{-- Global --}}
<script src="{{ asset('/plugins/global/plugins.bundle.js') }}"></script>
<script src="{{ asset('/js/scripts.bundle.js') }}"></script>
<script>
    @if(session()->has('feedback'))
        @php $feedback = session()->get('feedback'); @endphp

        @if(session()->get('feedback.type') == 'toastr')
            toastr.{{ $feedback['action'] }}('{{ $feedback["message"] }}')
        @else
            swal(
                '{{ $feedback["message"] }}',
                '{{ $feedback["action"] }}'
            )
        @endif
    @endif
</script>

<!--ALERTAS-->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

@if(session()->has('jsAlert'))
                <script>
                 swal("Genial!","{{ session()->get('jsAlert') }}","success");
                </script>
             @endif 

             @if(session()->has('jsAlerterror'))
                <script>
                 swal("Error!","{{ session()->get('jsAlerterror') }}","error");
                </script>
             @endif 
{{-- Quill --}}
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

{{-- Custom --}}
<script src="{{ asset('/js/custom/widgets.js') }}"></script>
<script src="{{ asset('/js/custom/modals.js') }}"></script>
<script src="{{ asset('/js/custom/apps/chat/chat.js') }}"></script>
<script src="{{ asset('/js/custom/modals/create-app.js') }}"></script>

{{-- TinyMCE --}}
<script src="https://cdn.tiny.cloud/1/tjhhn0wa38v5gyiaf57bjtklp4fmg1qlelnmckc9auplzze9/tinymce/5/tinymce.min.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/29.1.0/classic/ckeditor.js"></script>

{{-- File Input --}}
<script src="{{ asset('/js/vendor/piexif.min.js') }}"></script>
<script src="{{ asset('/js/vendor/sortable.min.js') }}"></script>
<script src="{{ asset('/js/vendor/fileinput.min.js') }}"></script>
<script src="{{ asset('/js/vendor/theme.min.js') }}"></script>
<script src="{{ asset('/js/vendor/fileinput.es.js') }}"></script>

{{-- Dual Listbox --}}
<script src="{{ asset('/js/vendor/jquery.bootstrap-duallistbox.min.js?v=') . env('APP_VERSION') }}"></script>

{{-- DataTables --}}
<!-- <script>var HOST_URL = "/metronic/theme/html/tools/preview";</script> -->
<script src="{{ asset('/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script src="{{ asset('/js/pages/crud/datatables/extensions/index.js') }}"></script>

<!-- <script src="{{ asset('/js/pages/crud/datatables/extensions/buttons.js') }}"></script> -->
<script>

    $.extend( true, $.fn.dataTable.defaults, {
        dom:  $(location).attr("href").indexOf('dashboard') > -1 ? 'Brtip' : 'B<"toolbar">rtip',
        buttons: [
				        { extend: 'excelHtml5',
                  className: 'export_excel btn-bg-light btn-color-muted',
                  init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                  }
                },
                { extend: 'csvHtml5',
                  className: 'export_csv btn-bg-light btn-color-muted',
                  init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                  }
                },
                { extend: 'pdfHtml5',
                  className: 'export_pdf btn-bg-light btn-color-muted',
                  init: function(api, node, config) {
                    $(node).removeClass('btn-secondary')
                  }
                }
			],
    } );

    $('#export_excel').on('click', function(e) {
		e.preventDefault();
        $('.export_excel').click();
	});

	$('#export_csv').on('click', function(e) {
		e.preventDefault();
		$('.export_csv').click();
	});

	$('#export_pdf').on('click', function(e) {
		e.preventDefault();
		$('.export_pdf').click();
	});

</script>

{{-- Custom Scripts --}}
<script src="{{ asset('custom/js/main.js') }}"></script>
<script src="{{ asset('custom/js/fakit.js') }}"></script>

resources/views/admin/layouts/partials/sidebar.blade.php
<div id="kt_aside" class="aside aside-dark aside-hoverable" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle">
	<div class="aside-logo flex-column-auto" id="kt_aside_logo">
		<a href="{{ route('dashboard.index') }}">
			<img alt="Logo"  src="{{ asset(env('DOMAIN_LOGO_URL')) }}" class="logo" style="height: 45px" />
		</a>
		<div id="kt_aside_toggle" class="btn btn-icon w-auto px-0 btn-active-color-info aside-toggle" data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body" data-kt-toggle-name="aside-minimize">
			 <span class="svg-icon svg-icon-1 rotate-180">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                    <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg>
			</span>
		</div>
	</div>


	<div class="aside-menu flex-column-fluid">
		<div class="hover-scroll-overlay-y my-5 my-lg-5" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer" data-kt-scroll-wrappers="#kt_aside_menu" data-kt-scroll-offset="0">
			<div class="menu menu-column menu-title-gray-800 menu-state-title-info menu-state-icon-info menu-state-bullet-info menu-arrow-gray-500" id="#kt_aside_menu" data-kt-menu="true">
				<div class="menu-item">
					<div class="menu-content pb-2">
						<span class="menu-section text-muted text-uppercase fs-8 ls-1">Dashboard</span>
					</div>
				</div>

                <div class="menu-item">
					<a class="menu-link active" href="{{ route('dashboard.index') }}">
                        <span class="menu-icon">
                            <i class="fa fa-home fs-5"></i>
                        </span>
                        <span class="menu-title">Dashboard</span>
					</a>
				</div>

				<!-- EVENTS -->
				<div class="menu-item">
					<div class="menu-content pt-8 pb-2">
						<span class="menu-section text-muted text-uppercase fs-8 ls-1">EVENTOS</span>
					</div>
				</div>

                <div data-kt-menu-trigger="click" class="menu-item menu-accordion">
					<span class="menu-link">
						<span class="menu-icon">
                            <i class="fa fa-scroll fs-5"></i>
						</span>
						<span class="menu-title">Eventos</span>
						<span class="menu-arrow"></span>
					</span>

					<div class="menu-sub menu-sub-accordion menu-active-bg">
						<div class="menu-item">
							<a class="menu-link" href="{{ route('events.index') }}#create">
                                <span class="menu-icon">
                                    <i class="fa fa-plus-circle"></i>
                                </span>
								<span class="menu-title">Agregar Nuevo</span>
							</a>
						</div>
						<div class="menu-item">
							<a class="menu-link" href="{{ route('events.index') }}">
                                <span class="menu-icon">
                                    <i class="fa fa-list-ol"></i>
                                </span>
								<span class="menu-title">Todos los Eventos</span>
							</a>
						</div>
					
					</div>
			    </div>

				<!-- USERS -->
				<div class="menu-item">
					<div class="menu-content pt-8 pb-2">
						<span class="menu-section text-muted text-uppercase fs-8 ls-1">USUARIOS</span>
					</div>
				</div>

                <div data-kt-menu-trigger="click" class="menu-item menu-accordion">
					<span class="menu-link">
						<span class="menu-icon">
                            <i class="fa fa-user-alt fs-5"></i>
						</span>
						<span class="menu-title">Usuarios</span>
						<span class="menu-arrow"></span>
					</span>

					<div class="menu-sub menu-sub-accordion menu-active-bg">
						<div class="menu-item">
							<a class="menu-link" href="{{ route('users.index') }}#create">
                                <span class="menu-icon">
                                    <i class="fa fa-file-csv fs-5"></i>
                                </span>
								<span class="menu-title">Cargar Usuarios</span>
							</a>
						</div>
						<div class="menu-item">
							<a class="menu-link" href="{{ route('users.index') }}">
                                <span class="menu-icon">
                                    <i class="fa fa-list-ol"></i>
                                </span>
								<span class="menu-title">Todos los Usuarios</span>
							</a>
						</div>
					
					</div>
			    </div>
			

	
                <!-- OTROS -->
				<div class="menu-item">
					<div class="menu-content">
				    	<div class="separator mx-1 my-4"></div>
					</div>
				</div>
				<div class="menu-item">
					<a class="menu-link" href="{{ route('events.allEvents') }}">
                        <span class="menu-icon">
						<i class="fas fa-file-chart-line fs-3"></i>
                        </span>
                        <span class="menu-title">REPORTES</span>
					</a>
				</div>
			</div>
		</div>
	</div>

</div>

resources/views/admin/layouts/partials/toolbar.blade.php
<div class="toolbar" id="kt_toolbar">
	<div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
		<div data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}" class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
			<h1 class="d-flex align-items-center text-dark fw-bolder fs-3 my-1">
				@if($title == 'Dashboard')
					Panel
					<span class="h-20px border-gray-200 border-start ms-3 mx-2"></span>
						<small class="text-muted fs-7 fw-bold my-1 ms-1">{{ auth()->user()->getRoleNames()[0]  }}</small>
				@else
					@if(isset($filter) && $filter == 'all')
						<small class="text-muted fs-7 fw-bold my-1 ms-1">Todos los Obituarios</small>
					@elseif(isset($filter) && $filter != 'all')
						<small class="text-muted fs-7 fw-bold my-1 ms-1">Obituarios por {{ $filter }}</small>
					@endif
				@endif				
			</h1>
		</div>
		<div class="d-flex align-items-center py-1">
			@if(isset($title_secondary) && $title_secondary == 'obituaries')
				<a href="{{ route('obituaries.index', ['filter_time' => 'today', 'filter' => $filter]) }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('obituaries.index', ['filter_time' => 'current_month', 'filter' => $filter]) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('obituaries.index', ['filter_time' => 'current_year', 'filter' => $filter]) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@elseif(isset($title_secondary) && $title_secondary == 'obituaries_not_approved')
				<a href="{{ route('obituaries.not_approved') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('obituaries.not_approved', ['filter_time' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('obituaries.not_approved', ['filter_time' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@elseif(isset($title_secondary) && $title_secondary == 'obituaries_personal')
				<a href="{{ route('obituaries.personal') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('obituaries.personal', ['filter_time' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('obituaries.personal', ['filter_time' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@elseif(isset($title_secondary) && $title_secondary == 'obituaries_billing')
				<a href="{{ route('obituaries.billing') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('obituaries.billing', ['filter_time' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('obituaries.billing', ['filter_time' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@elseif(isset($title_secondary) && $title_secondary == 'condolences')
				<a href="{{ route('condolences.index') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('condolences.index', ['filter_time' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('condolences.index', ['filter_time' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@elseif(isset($title_secondary) && $title_secondary == 'condolences_not_approved')
				<a href="{{ route('condolences.not_approved') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('condolences.not_approved', ['filter_time' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('condolences.not_approved', ['filter_time' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@else				
				<a href="{{ route('dashboard.index') }}" id="today" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Día
                </a>
				<a href="{{ route('dashboard.index', ['filter' => 'current_month']) }}" id="current_month" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
				    Mes
                </a>
				<a href="{{ route('dashboard.index', ['filter' => 'current_year']) }}" id="current_year" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                    Año
                </a>
			@endif
            <a href="#" id="reportrange" class="btn btn-active-light-info btn-color-muted btn-sm font-weight-bold font-size-base mr-1" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end">
                <i class="fa fa-calendar"></i>&nbsp;
                <span></span> <i class="fa fa-caret-down"></i>
            </a>
		</div>
	</div>
</div>